name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (matching your local version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Ensure it matches your local setup

      # Debug mode to track any issues
      - name: Enable Debug Mode
        run: set -x

      # Run the snake contribution generator
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: yeniObabatunde
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Check Git status to confirm changes
      - name: Check Git Status
        run: |
          git status
          ls -lah dist

      # Commit and push changes to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Updated GitHub contribution snake" || echo "No changes to commit"
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to GitHub Pages (if needed)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
